import { ROLES } from "./roles";
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USERS,
    PERMISSIONS.EDIT_USERS,
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.VIEW_CRM,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_INVOICE,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_CRM,
    PERMISSIONS.VIEW_INVOICE,
  ],

  [ROLES.MR]: [
    PERMISSIONS.VIEW_CRM,
    PERMISSIONS.VIEW_INVOICE,
  ],

  [ROLES.DOCTOR]: [
    PERMISSIONS.VIEW_CRM,
  ],

  [ROLES.DISTRIBUTOR]: [
    PERMISSIONS.VIEW_INVENTORY,
  ],
};